#!/bin/sh
# usage: check1fuzz <fuzzer stimulus file>
# fuzz check script, for checking that one fuzz input works

set -e
: ${srcdir=.}
. "$srcdir"/shlib

fuzzfile="$1"

exec <"$fuzzfile"

case "$fuzzfile" in
fuzz-*)		desc="${fuzzfile#fuzz-}"	;;
fuzzraw-*)	desc="${fuzzfile#fuzzraw-}"	;;
esac

read nargs
if [ "$nargs" = 0 ]; then printf "SKIPPED-$desc "; exit 5; fi

read arg1len
read program

case "$program" in
*/*)	;;
*)	program="./$program" ;;
esac

set +e
${program} <"$fuzzfile" >/dev/null 2>&1
rc=$?
set -e

if [ $rc != 0 ]; then
	printf >&2 '\nFAIL-%s\n' $fuzzfile
	exit $rc
fi

printf "$desc "
